volatile float Time_period;
volatile int count;
volatile float Set_rpm = 0;
volatile float Previous_error = 0;
volatile float D_error = 0;
volatile float I_error = 0;
volatile float P_gain = 0.65;
volatile float I_gain = 0.005;
volatile float D_gain = 0.005;
volatile float Dt = 0.5;
volatile float Error;
volatile float Required_rpm;
volatile float Present_rpm;
volatile float H;
volatile float I;
volatile float P;
volatile float D;
volatile float M;
volatile float Total_error;
volatile int Final;
